# Use official Node.js 18 image as base
FROM node:18

# Set the working directory for client
WORKDIR /app/client

# Copy package.json and package-lock.json for client
COPY client/package*.json ./

# Install client dependencies
RUN npm i

# Copy the rest of the client application
COPY client/ .

# Expose port for Node.js client
EXPOSE 3000

# Start the client application
CMD ["npm", "run", "dev"]
