[server]
port = 4000
host = '0.0.0.0'  # To allow all IP access, use '0.0.0.0'; default is '127.0.0.1'

[database]
username = "arden_dev"
password = "arden_dev"
address = "10.140.6.7"  # Enclose the IP address in double quotes
port = 5432
database = "arden_dev"  # Enclose the database name in double quotes

[access]
username = "tanbin"
password = "tanbin"
address = "192.168.10.61"
port = 1433
database = "CPSStandardBank"

[cbs]
username = "adc"
password = "adc123"
url = "10.130.117.117:1523/ibpdb"


[database_Cloud]
username = "sql12666632"
password = "HiYs4tP6lf"
address = "sql12.freemysqlhosting.net"
port = 3306
database = "sql12666632"
