[server]
port = 4000
host = '0.0.0.0'  # To allow all IP access, use '0.0.0.0'; default is '127.0.0.1'

[database]
username = "postgres"
password = "root"
address = "127.0.0.1"  # Enclose the IP address in double quotes
port = 5432
database = "postgres"  # Enclose the database name in double quotes

[access]
username = "tanbin"
password = "tanbin"
address = "192.168.10.61"
port = 1433
database = "CPSStandardBank"

[cbs]
username = "adc"
password = "adc123"
url = "10.130.117.117:1523/ibpdb"
