[server]
port = 4000
host = '0.0.0.0'  # To allow all IP access, use '0.0.0.0'; default is '127.0.0.1'

[database]
username = "sql12666632"
password = "HiYs4tP6lf"
address = "sql12.freemysqlhosting.net"  # Enclose the IP address in double quotes
port = 3306
database = "sql12666632"  # Enclose the database name in double quotes
